src/Spryker/Client/RabbitMq/RabbitMqConfig.php
src/Spryker/Client/RabbitMq/RabbitMqDependencyProvider.php

* Move queue configuration to bundle config
* In the next minor release all configs will move to `BundleConfig` instead of `BundleDependencyProvider` 
* Merging Soon (WIP) :https://github.com/spryker/rabbit-mq/pull/4

RabbitMq Config Issue

---

composer.json

Fix wrong PSR in autoload

---

.editorconfig
.travis.yml
composer.json
src/Spryker/Client/RabbitMq/Model/Connection/Connection.php
src/Spryker/Client/RabbitMq/Model/Connection/ConnectionInterface.php
src/Spryker/Client/RabbitMq/Model/Consumer/Consumer.php
src/Spryker/Client/RabbitMq/Model/Helper/QueueEstablishmentHelper.php
src/Spryker/Client/RabbitMq/Model/Helper/QueueEstablishmentHelperInterface.php
src/Spryker/Client/RabbitMq/Model/Manager/Manager.php
src/Spryker/Client/RabbitMq/Model/Publisher/Publisher.php
src/Spryker/Client/RabbitMq/Model/RabbitMqAdapter.php
src/Spryker/Client/RabbitMq/RabbitMqClient.php
src/Spryker/Client/RabbitMq/RabbitMqClientInterface.php
src/Spryker/Client/RabbitMq/RabbitMqConfig.php
src/Spryker/Client/RabbitMq/RabbitMqDependencyProvider.php
src/Spryker/Client/RabbitMq/RabbitMqFactory.php
src/Spryker/Shared/RabbitMq/RabbitMqConstants.php

Fix travis

---

.gitignore
.travis.yml
README.md
composer.json
src/Spryker/Zed/RabbitMq/Communication/Console/DeleteAllExchangesConsole.php
src/Spryker/Zed/RabbitMq/Communication/Console/DeleteAllQueuesConsole.php
src/Spryker/Zed/RabbitMq/Communication/Console/PurgeAllQueuesConsole.php

php7.1+.
namespace fix
url fix

Fix composer json

---

src/Spryker/Client/RabbitMq/Model/Consumer/Consumer.php
src/Spryker/Client/RabbitMq/Model/Helper/QueueEstablishmentHelper.php
src/Spryker/Client/RabbitMq/Model/Publisher/Publisher.php
src/Spryker/Client/RabbitMq/RabbitMqConfig.php
src/Spryker/Client/RabbitMq/RabbitMqFactory.php
src/Spryker/Shared/RabbitMq/Transfer/rabbitmq.transfer.xml

- Developer(s): @ehsanmx
- Ticket: https://spryker.atlassian.net/browse/CC-116
- Academy PR: ACADEMY_URL_HERE
- Release Group: URL_HERE
This release contains several updates:
- Supports rabbit-mq x-[options] now
- Fixed routing issue in some cases in batch operation
- Fixed persistence delivery mode as default
_**Minor:** Added functionality in a backwards-compatible manner_
Def of done (by responsible developer):
Improvements
- Added necessary configs to support x-options
- Fixed issues in queue connection and sendMessages()

Feature/cc 116/master optimizing data importer speed

---

src/Spryker/Client/RabbitMq/Model/Connection/Connection.php
src/Spryker/Client/RabbitMq/Model/Consumer/Consumer.php
src/Spryker/Client/RabbitMq/RabbitMqDependencyProvider.php
src/Spryker/Zed/RabbitMq/Business/Model/Exchange/ExchangeInfo.php
src/Spryker/Zed/RabbitMq/Communication/Console/DeleteAllExchangesConsole.php
src/Spryker/Zed/RabbitMq/Communication/Console/DeleteAllQueuesConsole.php
src/Spryker/Zed/RabbitMq/Communication/Console/PurgeAllQueuesConsole.php
src/Spryker/Zed/RabbitMq/Communication/Console/SetUserPermissionsConsole.php
src/Spryker/Zed/RabbitMq/RabbitMqDependencyProvider.php

CS Fixes to make possible release this PR: https://github.com/spryker/rabbit-mq/pull/25

TE-28: CS fixes

---

src/Spryker/Client/RabbitMq/Model/Consumer/Consumer.php

- Developer(s): @asaulenko
- Ticket: https://spryker.atlassian.net/browse/TE-623
- Academy PR: -
- Release Group: https://release.spryker.com/release-groups/view/1154
Added the ability to reset consumers message processing callback after each call
Optimized message processing in terms of memory consumption
Improvements
- Changed `Spryker\Client\RabbitMq\Model\Consumer\Consumer:: receiveMessages ` to reset callbacks array on each call
- Adjusted `Spryker\Client\RabbitMq\Model\Consumer\Consumer` to reset consumed messages after …

TE-623 RabbitMQ consumer callback issue

---

composer.json
src/Spryker/Client/RabbitMq/Model/Connection/ConnectionFactory.php
src/Spryker/Shared/RabbitMq/Transfer/rabbitmq.transfer.xml

- Developer(s): @a-sabaa
- Ticket: TICKET_URL_HERE
- Academy PR: ACADEMY_URL_HERE
- Release Group: https://release.spryker.com/release-groups/view/1470
{skip}
Improvements
- Added all `PhpAmqpLib\Connection\AMQPStreamConnection` constructor parameter defaults to class creation in factory
- Added all constructor parameters to `Generated\Shared\Transfer\QueueConnectionTransfer`
- Defaulted HeartBeat for `PhpAmqpLib\Connection\AMQPStreamConnection` creation to `0`

fixed php-amqplib composer version

---

src/Spryker/Client/RabbitMq/Model/Helper/QueueEstablishmentHelper.php
src/Spryker/Shared/RabbitMq/Transfer/rabbitmq.transfer.xml

- Developer(s): @m7moud
- Ticket: https://spryker.atlassian.net/browse/CC-3572
- Academy PR: -
- Release Group: https://release.spryker.com/release-groups/view/1486
{skip}
Improvements
- Adjusted `RabbitMqOptionTransfer` object property `noWait` type to boolean.

CC-3572 Fix transfer noWait property type

---

.travis.yml
composer.json
phpstan.neon
src/Spryker/Client/RabbitMq/Model/Consumer/Consumer.php
src/Spryker/Client/RabbitMq/Model/Publisher/Publisher.php
src/Spryker/Zed/RabbitMq/Business/RabbitMqBusinessFactory.php

- Developer(s): @gechetspr
- Ticket: https://spryker.atlassian.net/browse/TE-3890
- Release https://release.spryker.com/release/pull-request-core/RabbitMq/42
RabbitMq              | patch                 |                       |
{skip}
Improvements
- Added PHP 7.4 support.

TE-4417 Update standalone modules for php 7.4

---

.travis.yml
README.md
composer.json

WIP
will be merged once core is all done here.

TE-4334 raised minimum version of php to 7.2

---

composer.json
src/Spryker/Client/RabbitMq/Model/Connection/ConnectionBuilder/ConnectionBuilder.php
src/Spryker/Client/RabbitMq/RabbitMqConfig.php
src/Spryker/Shared/RabbitMq/RabbitMqEnv.php
src/Spryker/Shared/RabbitMq/Transfer/rabbit_mq.transfer.xml

- Developer(s): @jacoz
- Ticket: https://spryker.atlassian.net/browse/TE-4788
- Release Group: https://release.spryker.com/release-groups/view/2124
{skip}
Improvements
- Added the possibility to configure stream context options for secure connections.
- Introduced `RabbitMqEnv::RABBITMQ_STREAM_CONTEXT_OPTIONS` config.
- Introduced `QueueConnectionTransfer.streamContextOptions` transfer property.

TE-4789 - Implement TLS confugiratiuon for RMQ

---

composer.json
src/Spryker/Client/RabbitMq/RabbitMqDependencyProvider.php
src/Spryker/Zed/RabbitMq/RabbitMqDependencyProvider.php

- Developer(s): @DmitryLymarenko
- Ticket: https://spryker.atlassian.net/browse/TE-7003
- Release Group: https://release.spryker.com/release-groups/view/2913
- Release Overview: https://release.spryker.com/release/pull-request-core/RabbitMq/51
RabbitMq              | patch                 |                       |
Improvements
- Fixed `php-amqplib` dependency version to what is actually needed.
- Adjusted `RabbitMqDependencyProvider::addStoreClient()` to use setter instead of array access.
- Adjusted `RabbitMqDependencyProvider::addQueueAdapter()` to use setter instead of array access.
- Adjusted …

TE-7198 Add possibility to run travis with prefer-lowest

---

.travis.yml
composer.json
src/Spryker/Zed/RabbitMq/Communication/Console/DeleteAllExchangesConsole.php
src/Spryker/Zed/RabbitMq/Communication/Console/DeleteAllQueuesConsole.php
src/Spryker/Zed/RabbitMq/Communication/Console/PurgeAllQueuesConsole.php
src/Spryker/Zed/RabbitMq/Communication/Console/SetUserPermissionsConsole.php
tests/SprykerTest/Client/RabbitMq/codeception.yml
tests/SprykerTest/Zed/RabbitMq/codeception.yml

- Developer(s): @stereomon
- Ticket: https://spryker.atlassian.net/browse/TE-7001
- Academy PR: ACADEMY_URL_HERE
- Release Group: https://release.spryker.com/release-groups/view/2897
RabbitMq              | minor               |                       |
Fixes
- Always return `int` for console command.

TE-7001 Updated symfony console commands to always return int.

---

.gitattributes
psalm-report.json
src/Spryker/Client/RabbitMq/Model/Publisher/Publisher.php

https://spryker.atlassian.net/browse/TE-8110

TE-8110 Fix param mismatch

---

.github/workflows/ci.yml
src/Spryker/Client/RabbitMq/Model/Connection/Connection.php
src/Spryker/Client/RabbitMq/Model/Connection/ConnectionManager.php

Updated github actions configuration.

TE-8554 Updated github actions configuration.

---

phpstan.neon
src/Spryker/Client/RabbitMq/RabbitMqConfig.php

Ticket: https://spryker.atlassian.net/browse/TE-10993

TE-10993 Fix up generics phpdoc-blocks.

---

.github/workflows/ci.yml
README.md
composer.json
dependency.json

Ticket: https://spryker.atlassian.net/browse/FRW-332

FRW-332 Change min PHP version to 8.0

---

.github/workflows/ci.yml
composer.json

Removed library usage until further change to the release process is made

Remove composer lowest check

---

CONTRIBUTING.md

https://spryker.atlassian.net/browse/FRW-8526

FRW-8526 Added CONTRIBUTING.md.

---

.github/workflows/ci.yml
README.md
composer.json

https://spryker.atlassian.net/browse/FRW-8801

FRW-8801 Dropped PHP 8.1 support.
